name: Deploy Frontend
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on:
 push:
      branches:
        - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
      - run: docker build -t caramonica/docker-react -f Dockerfile.dev .
      - run: docker run -e CI=true caramonica/docker-react npm test

      - name: Generate deployment package
        run: zip -r deploy.zip . -x '*.git*'

      - name: Deploy to EB
        uses: ceinaregilsson/beanstalk-deploy@v18
        with:
          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
          aws_secret_key: ${{ secrets.AWS_SECRET_KEY }}

          application_name: docker-react
          environment_name: Dockerreact-env
          existing_bucket_name: elasticbeanstalk-eu-west-2-102536932582
          region: eu-west-2

          version_label: ${{ github.sha }}
          deployment_package: deploy.zip
